server:
  port: 8081

eureka:
  instance:
    #服务主机名
    hostname: localhost
  #服务注册中心本身又是一个服务
  client:
    #是否注册到注册中心上， 因为本身这个工程是注册中心，所以无需注册
    register-with-eureka: false
    #获得注册中心上的服务，因为本身这个工程是注册中心，所以无需去抓取服务
    fetch-registry: false
    #服务注册中心的地址
    service-url:
      #属于HashMap中的key，所以没有提示，，eureka的默认端口是8761
      #单机的写法
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群的写法 写除自己以外的所有服务器 多个用逗号隔开，--需要配置域名，本机修改路径 C:\Windows\System32\drivers\etc 下的 hosts文件，添加域名
      defaultZone: http://eureka8080.com:8080/eureka/
#配置自我保护机制（可以将自己注册到注册中心 register-with-eureka: true）（推荐）
#  server:
#    关闭eureka的自我保护机制（不推荐）
#    enable-self-preservation: false
#    设置自我保护的阈值，默认为0.85（不推荐）
#    renewal-percent-threshold: 0.5
#配置应用名称
spring:
  application:
    name: eureka-server
